[package]
name = "invoice-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
sheets4 = { version = "2.0.8", package = "google-sheets4" }
oauth2 = { version = "5.1.0", package = "yup-oauth2" }
# google-drive = "0.2.4"
serde = "1.0.136"
serde_json = "1.0.78"
